### ISSUE TITLE
kotlin+maven: Cannot find implementation for org.mapstruct.example.kotlin.converter.PersonConverter

### ISSUE THREAD

**Issue by howieyuen** [mapstruct/mapstruct-examples#152]
I clone this repo, and run `org/mapstruct/example/kotlin/Main.kt` and got this:

```
Exception in thread "main" java.lang.RuntimeException: java.lang.ClassNotFoundException: Cannot find implementation for org.mapstruct.example.kotlin.converter.PersonConverter
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:61)
	at org.mapstruct.example.kotlin.MainKt.main(Main.kt:10)
Caused by: java.lang.ClassNotFoundException: Cannot find implementation for org.mapstruct.example.kotlin.converter.PersonConverter
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:75)
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:58)
	... 1 more
```

**Comment by howieyuen** [comment]
oops, I clean the build cache, compile it again, runs ok
