### ISSUE TITLE
Exception running mapstruct-examples-lombok

### ISSUE THREAD

**Issue by fedy2** [mapstruct/mapstruct-examples#23]
I'm trying to run the lombok example using the unit test class SourceTargetMapperTest but I get the following exception:

`java.lang.ExceptionInInitializerError
	at com.mycompany.mapper.SourceTargetMapperTest.testMapping(SourceTargetMapperTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Cannot find implementation for com.mycompany.mapper.SourceTargetMapper
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:79)
	at com.mycompany.mapper.SourceTargetMapper.<clinit>(SourceTargetMapper.java:31)
	... 24 more
Caused by: java.lang.ClassNotFoundException: Cannot find implementation for com.mycompany.mapper.SourceTargetMapper
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:93)
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:76)
	... 25 more

`

I'm using Eclipse STS 3.8.3.

**Comment by filiphr** [comment]
Are you talking about the [mapstruct-lombok](https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-lombok) example? It works via Maven and IntelliJ. Can you check if eclipse is creating calling the APT and if the `SourceTargetMapperImpl` is created correctly. If it is not, then it is some problem with Eclipse

**Comment by agudian** [comment]
For Eclipse to pick up the annotation processor config automatically, you need to have the [m2e-apt plugin](https://marketplace.eclipse.org/content/m2e-apt) installed and configured to use the JDT APT variant.

**Comment by hazemkmammu** [comment]
Getting the following exception 
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.mycompany.mapper.Main.main(Main.java:17)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Cannot find implementation for com.mycompany.mapper.SourceTargetMapper
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:61)
	at com.mycompany.mapper.SourceTargetMapper.<clinit>(SourceTargetMapper.java:18)
	... 1 more
Caused by: java.lang.ClassNotFoundException: Cannot find implementation for com.mycompany.mapper.SourceTargetMapper
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:75)
	at org.mapstruct.factory.Mappers.getMapper(Mappers.java:58)
	... 2 more
```
Using `Spring Tool Suite 4.11.0.RELEASE (BuildId: 202106180608)` which is based on `Eclipse 4.20.0.v20210611-1600`.

 'mapstruct-lombok' is imported into the workspace as a Gradle project. 

The bundled Gradle wrapper which uses version 6.2 throws an error on import, so used Gradle 7.1.1 instead.

I assume the advice on m2e-apt-plugin is only relevant to maven.

Any thoughts on this?

**Comment by Zegveld** [comment]
for eclipse-gradle integration see https://mapstruct.org/documentation/ide-support/

**Comment by filiphr** [comment]
Thanks @Zegveld, closing this for now
